import { Inter } from 'next/font/google';
import './globals.css';
import { AppBar, Toolbar, Typography, Container } from '@mui/material';
import { NavigationDrawer } from '../components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const navigationLinks = [
    { text: 'Home', href: '/' },
    { text: 'Produtos', href: '/products' },
    { text: 'Cadastrar Produto', href: '/create' },
    { text: 'Vendas', href: '/sales' },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar position="static">
          <Toolbar>
            <NavigationDrawer links={navigationLinks} />
          </Toolbar>
        </AppBar>
        <Container style={{ marginTop: '20px' }}>{children}</Container>
        <footer style={{ marginTop: '20px', textAlign: 'center' }}>© 2024 Minha Empresa</footer>
      </body>
    </html>
  );
}
