import { Inter } from 'next/font/google';
import './globals.css';
import { Container } from '@mui/material';
import { DynamicNavigationLayout } from '../components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const navigationLinks = [
    { text: 'Home', href: '/' },
    { text: 'Produtos', href: '/products' },
    { text: 'Vendas', href: '/sales' },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicNavigationLayout navigationLinks={navigationLinks}>
          <Container style={{ marginTop: '20px' }}>{children}</Container>
        </DynamicNavigationLayout>
        <footer style={{ marginTop: '20px', textAlign: 'center' }}>© 2024 Minha Empresa</footer>
      </body>
    </html>
  );
}
